
#
# Absoft Developer Tools Interface requires use of this makefile.
#
MKDIR=if not exist "$(OBJDIR)\nul" mkdir 
RMDIR=rmdir /S /Q

#
# Variables for the compiler(s) and linker
#
ABSOFT_F95=f95
ABSOFT_F77=f95
VAST_PREPROCESSOR=vastfp.exe 
RC=rc.exe
CL=cl.exe
ABSOFT_F95_LINKER=f95
DUMMY=

#
# Flags
#
ABSOFT_F95_FLAGS=-m32 -O2
ABSOFT_F77_FLAGS=-O2 -m32 -f77_compat
RC_FLAGS=
CL_FLAGS=-O2
ABSOFT_F95_LINKER_FLAGS=-m32 -O2

#
# Name of the executable
#
TARGET=ionort_chapman_wf.exe
OUTDIR=.
OBJDIR=.\Release

#
# Files for this executable
#
VAST_PREPROCESSOR_FILES=
ABSOFT_F95_FILES=
ABSOFT_F77_FILES="ionort_chapman_wf.for"
CL_FILES=
ABSOFT_F95_LINKER_FILES=
RC_FILES=

#
# Rules and dependencies for the executable
#
SRCFILES=$(ABSOFT_F77_FILES)
OBJFILES="$(OBJDIR)\ionort_chapman_wf.obj"
all: "$(OUTDIR)\$(TARGET)"
	

"$(OUTDIR)\$(TARGET)": "$(OBJDIR)" $(OBJFILES) $(USER_LIBS) $(MODFILES) $(RC_FILES)
	$(ABSOFT_F95_LINKER) $(ABSOFT_F95_LINKER_FLAGS) $(LPATHS) $(OBJFILES) $(ABSOFT_F95_LINKER_FILES) $(LIBS) -o "$(OUTDIR)\$(TARGET)"



"$(OBJDIR)\ionort_chapman_wf.obj": "ionort_chapman_wf.for"
	$(ABSOFT_F77) -c -nowdir $(ABSOFT_F77_FLAGS) -o "$(OBJDIR)\ionort_chapman_wf.obj" "ionort_chapman_wf.for"

"$(OBJDIR)":
	$(MKDIR) "$(OBJDIR)"
#
# Clean Rules
#
clean:
	 if exist "$(OBJDIR)" $(RMDIR) "$(OBJDIR)" 
	 if exist "$(TARGET)" erase "$(TARGET)"

#
# Define necessary macros for dependency scanning.
#
MKDEP=amakedepend
MKDEP_FLAGS= -quiet "-pre$(OBJDIR)\"\" -Y -modInfo -errdel -f90 -f makefile 
#
# Generate dependencies for the project
#
ScanAll: "$(OUTDIR)" "$(OBJDIR)" MakeDepsAll

#
# Scan for all F77, F95, and c/c++ dependencies
#
MakeDepsAll:
	$(MKDEP) "@C:\Documents and Settings\Administrator\Desktop\Paper 2\IONORT Copy\FORTRAN\ionort_chapman_wf\Release\mkdep_F77"
# DO NOT DELETE THIS LINE - makedepend depends upon it.


